### ISSUE TITLE
Submitting Tip Calculate prework for iOS coderschool course

### ISSUE THREAD

**Issue by quocnguyen** [quocnguyen/awesometips#1]
Here is my completed prework !
Thanks you

/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Swift submission, quocnguyen!

 :laughing: Everything looks good with the format of your submission. We'll be reviewing your submission soon!

**Comment by coderschoolreview** [comment]
:+1:  Nice job with the Tip Calculator! 

### Quick Comments:
- Basically your app works fine.
- Good usage of `NSUserDefaults`. This is one of the methods to pass the data from multiple viewControllers. 
- Your keyboard doesn't have the `.` then how can you type `$x.yz`

### Optional Suggestions to Improve
- Look into the `UIView.animateWithDuration` functions to add animations.
